# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'GitHub Pages'
description: 'GitHub Action to deploy to GitHub Pages'
author: 'crazy-max'
branding:
  color: 'green'
  icon: 'upload-cloud'

inputs:
  domain:
    description: 'Git domain (default github.com)'
    required: false
    default: 'github.com'
  repo:
    description: 'GitHub repository where assets will be deployed (default $GITHUB_REPOSITORY)'
    required: false
  target_branch:
    description: 'Git branch where assets will be deployed'
    default: 'gh-pages'
    required: false
  keep_history:
    description: 'Create incremental commit instead of doing push force'
    default: 'false'
    required: false
  allow_empty_commit:
    description: 'Allow an empty commit to be created'
    default: 'true'
    required: false
  build_dir:
    description: 'Build directory to deploy'
    required: true
  absolute_build_dir:
    description: 'Whether to treat build_dir as an absolute path'
    default: 'false'
    required: false
  follow_symlinks:
    description: 'If enabled, the content of symbolic links will be copied'
    default: 'false'
    required: false
  committer:
    description: 'The committer name and email address'
    required: false
  author:
    description: 'The author name and email address'
    required: false
  commit_message:
    description: 'Commit message'
    required: false
  fqdn:
    description: 'Write the given domain name to the CNAME file'
    required: false
  jekyll:
    description: 'Allow Jekyll to build your site'
    default: 'true'
    required: false
  dry_run:
    description: 'If enabled, nothing will be pushed'
    default: 'false'
    required: false
  verbose:
    description: 'Enable verbose output'
    default: 'false'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
