# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'GitHub Pages'
description: 'GitHub Action to deploy to GitHub Pages'
author: 'crazy-max'
branding:
  color: 'green'
  icon: 'upload-cloud'

inputs:
  repo:
    description: 'GitHub repository where assets will be deployed (default current)'
  target_branch:
    description: 'Git branch where assets will be deployed'
    default: 'gh-pages'
  keep_history:
    description: 'Create incremental commit instead of doing push force'
    default: 'false'
  allow_empty_commit:
    description: 'Allow an empty commit to be created'
    default: 'true'
  build_dir:
    description: 'Build directory to deploy'
    required: true
  committer_name:
    description: 'Commit author''s name'
  committer_email:
    description: 'Commit author''s email'
  commit_message:
    description: 'Commit message'
  fqdn:
    description: 'Write the given domain name to the CNAME file'

runs:
  using: 'node12'
  main: 'lib/main.js'
