name: cleanup

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write # required to remove git branch
    strategy:
      fail-fast: false
      matrix:
        branch:
          - gh-pages
          - gh-pages-keep
    steps:
      -
        name: Delete branch
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            await github.rest.git.deleteRef({
              ...context.repo,
              ref: "heads/${{ matrix.branch }}"
            });
